---
config:
  - name: well_monitoring
    description: Well monitoring parameters.
    type: gauge
    labels: [well, parameter]
    sequence:
      - time: 5
        time_wait: 1
        values: 63-64
        operation: set
        labels:
          well: 309
          parameter: Frequency_out
      - time: 5
        time_wait: 1
        values: 300-350
        operation: set
        labels:
          well: 309
          parameter: CurrentA_out
      - time: 5
        time_wait: 1
        values: 300-350
        operation: set
        labels:
          well: 309
          parameter: CurrentB_out
      - time: 5
        time_wait: 1
        values: 300-350
        operation: set
        labels:
          well: 309
          parameter: CurrentC_out
      - time: 5
        time_wait: 1
        values: 350-370
        operation: set
        labels:
          well: 309
          parameter: Voltage_out
      - time: 5
        time_wait: 1
        values: 350-420
        operation: set
        labels:
          well: 309
          parameter: VoltageAB_in
      - time: 5
        time_wait: 1
        values: 350-420
        operation: set
        labels:
          well: 309
          parameter: VoltageBC_in
      - time: 5
        time_wait: 1
        values: 350-420
        operation: set
        labels:
          well: 309
          parameter: VoltageCA_in
      - time: 5
        time_wait: 1
        values: 90-95
        operation: set
        labels:
          well: 309
          parameter: Motor_torque
      - time: 5
        time_wait: 1
        values: 32-36
        operation: set
        labels:
          well: 309
          parameter: Intake_pressure
      - time: 5
        time_wait: 1
        values: 90-95
        operation: set
        labels:
          well:
          parameter: Intake_temperature
      - time: 5
        time_wait: 1
        values: 110-115
        operation: set
        labels:
          well: 309add
          parameter: Motor_temperature
      - time: 5
        time_wait: 1
        values: 0-10
        operation: set
        labels:
          well: 309
          parameter: Vibration_x
      - time: 5
        time_wait: 1
        values: 0-10
        operation: set
        labels:
          well: 309
          parameter: Vibration_y