---
config:
  - name: well_monitoring
    description: Well monitoring parameters.
    type: gauge
    labels: [well, parameter]
    sequence:
      - time: 5
        time_wait: 1
        values: 40-60
        operation: inc
        labels:
          well: 309
          parameter: intake_pressure
      - time: 5
        time_wait: 1
        values: 80-100
        operation: inc
        labels:
          well: 309
          parameter: intake_temperature
      - time: 5
        time_wait: 1
        values: 1-10
        operation: inc
        labels:
          well: 309
          parameter: vibration_x
      - time: 5
        time_wait: 1
        values: 1-10
        operation: inc
        labels:
          well: 309
          parameter: vibration_y
